baseURL = 'https://last-war-cig.github.io/website/'
languageCode = 'en-us'
title = "Complete Idiot's Guide to Last War"
[module]
[[module.imports]]
path = 'github.com/thingsym/hugo-theme-techdoc'


[params]

    # Source Code repository section
    description = "Really, we mean it!"
    github_repository = "https://github.com/last-war-cig/website"
    version = "0.0.1-pre"
    menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]

    github_doc_repository = "https://github.com/last-war-cig/website"
    github_doc_repository_branch = "main"
    github_doc_repository_path = "content"
    
    algolia_search_enable = true
    algolia_indexName = "base"
    algolia_appId = "41TT3H6JJX"
    algolia_apiKey = "ecd306d57fe86f556dabba96852595d3" # Search-Only API Key
# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
        identifier = 'home'
    [[menu.main]]
        name = "Search"
        url = "/search"
        weight = 1

[outputs]
    home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]