baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Complete Idiot's Guide to Last War"
[module]
[[module.imports]]
path = 'github.com/thingsym/hugo-theme-techdoc'


[params]

    # Source Code repository section
    description = "Foo"
    github_repository = "https://github.com/last-war-cig/website"
    version = "1.0.1"
    menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]
# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
        identifier = 'home'

    [[menu.main]]
        name = "Twitter"
        url = "https://twitter.com/thingsym"
        weight = 2
        identifier = 'twitter'
        pre = "<b>pre!</b> "
        post = " <b>post!</b>"
        [menu.main.params]
          class = 'twitter-menu-item'